routes/api_customers.py
from flask import Blueprint, jsonify, request, redirect, url_for
from db import db
from models import Customer

# Create a Blueprint for the customers API
api_customers_bp = Blueprint("api_customers", __name__)


@api_customers_bp.route("/", methods=["GET"])
def get_customers():
    statement = db.select(Customer).order_by(Customer.name)
    records = db.session.execute(statement)
    results = records.scalars()
    return jsonify([cust.to_json() for cust in results])


@api_customers_bp.route("/<int:id>", methods=["PUT"])
def update_balance(id):
    data = request.get_json()
    customer = db.get_or_404(Customer, id)
    if "balance" not in data:
        return "Invalid Request", 405
    balance = data["balance"]
    if not isinstance(balance, (int, float)):
        return "Invalid Request", 405
    customer.balance = balance
    db.session.commit()
    return "", 204


@api_customers_bp.route("/<int:id>", methods=["DELETE"])
def delete_customer(id):
    customer = db.get_or_404(Customer, id)
    db.session.delete(customer)
    db.session.commit()
    return "", 204


@api_customers_bp.route("/api/customers", methods=["POST"])
def customers_json():
    # ! This method uses the form in my html so not as per the project instructions
    data = request.form.to_dict()
    customer = Customer(**data)
    db.session.add(customer)
    db.session.commit()
    return redirect(url_for("html.customers_info"))

routes/api_orders_bp.py
from flask import Blueprint, jsonify, request, redirect, url_for, render_template
from db import db
from models import Customer, Products, Order, ProductOrder

# Create a Blueprint for the customers API
api_order_bp = Blueprint("api_orders", __name__)


@api_order_bp.route("", methods=["POST"])
def add_order():
    data = request.get_json()
    if "customer_id" not in data:
        return "Invalid Request", 400
    customer_id = data["customer_id"]
    customer = db.get_or_404(Customer, customer_id)
    order = Order(customer=customer)
    db.session.add(order)
    for i in data["items"]:
        product_name = i["name"]
        statement = db.select(Products).where(Products.name == product_name)
        product = db.session.execute(statement).scalar()
        if product is None:
            # skip this product
            continue
        product = db.get_or_404(Products, product.id)

        quantity = i["quantity"]
        product_order = ProductOrder(order=order, product=product, quantity=quantity)
        db.session.add(product_order)

    db.session.commit()
    return "", 201


@api_order_bp.route("/<int:id>/delete", methods=["POST"])
def delete_order(id):
    order = db.get_or_404(Order, id)
    if order.processed is not None:
        return redirect(url_for("html.orders"))
    db.session.delete(order)
    db.session.commit()
    return redirect(url_for("html.orders"))


@api_order_bp.route("/<int:id>", methods=["PUT", "POST"])
def process_order(id):
    data = request.form.to_dict()
    print(data)
    order = db.get_or_404(Order, id)
    process = True
    if process:
        if "strategy" not in data:
            print("herejjj")
            strategy = "adjust"
        else:
            strategy = data["strategy"]
            print(strategy)
        print(strategy)
        if strategy not in ["adjust", "reject", "ignore"]:
            return "Invalid Request", 400
        if not order.process(strategy):
            return "Invalid Request", 400

    return redirect(url_for("html.orders"))

routes/html_bp.py
from flask import Blueprint, jsonify, request, redirect, url_for, render_template
from db import db
from models import Customer, Products, Order, ProductOrder

# Create a Blueprint for the customers API
htmls_bp = Blueprint("html", __name__)


@htmls_bp.route("/")
def home():
    return render_template(
        "home.html", name="Tanish", my_list=["Home", "Customers", "Products", "Orders"]
    )


@htmls_bp.route("/customers")
def customers_info():
    statement = db.select(Customer)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("customers.html", customers=results)


@htmls_bp.route("/customers/<int:id>", methods=["GET"])
def customer_info(id):
    customer = db.get_or_404(Customer, id)
    return render_template("customer.html", customer=customer)


@htmls_bp.route("/products")
def products_info():
    statement = db.select(Products)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("products.html", products=results)


@htmls_bp.route("/orders", methods=["GET"])
def orders():
    statement = db.select(Order)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("orders.html", orders=results)


@htmls_bp.route("/orders/<int:id>", methods=["GET"])
def orders_info(id):
    order = db.get_or_404(Order, id)
    return render_template("order.html", order=order)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Flask App</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="d-flex justify-content-around">
      <a class="btn btn-primary" href='{{url_for("html.home")}}'>Home</a>
      <a class="btn btn-primary" href='{{url_for("html.customers_info")}}'
        >Customers</a
      >
      <a class="btn btn-primary" href='{{url_for("html.products_info")}}'
        >Products</a
      >
      <a class="btn btn-primary" href='{{url_for("html.orders")}}'>Orders</a>
    </nav>
    {% block content %} {% endblock %}
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>
</html>

templates/customer.html
{% extends "base.html" %} {% block content %}
<h1>customer Info</h1>
<p>Name: {{customer.name}}</p>
<p>Phone: {{customer.phone}}</p>
<p>Balance: {{customer.balance}}</p>
<a href="{{url_for('html.customers_info')}}">Back</a>
{% for order in customer.orders %}
<p>Order: {{order.id}}</p>
<a href="{{url_for('html.orders_info', id=order.id)}}">Orders</a>
{%endfor%} {% endblock %}

templates/customers.html
{% extends "base.html" %}

{% block content %}
<h1>Customers</h1>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
    Add Customer
  </button>
  <!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Customer</h5>
            </div>
        <div class="modal-body">
          <form method="post" action='{{url_for("api_customers.customers_json")}}''>
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="mb-5">
              <label for="phone" class="form-label">Phone</label>
              <input type="text" class="form-control" id="phone" name="phone">
            </div>
            <div class="mb-3">
              <label for="balance" class="form-label">Balance</label>
              <input type="text" class="form-control" id="balance" name="balance">
            </div>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
        </div>
        </div>
    </div>
</div>
{% for customer in customers %}
<p>
    <span>{{ customer.name }}</span>
    <span>{{ customer.phone }}</span>
    <span>{{ customer.balance }}</span>
    <a href='{{url_for("html.customer_info", id=customer.id)}}'>Details</a>
</p>
{% endfor %}
<!-- Button trigger modal -->
{% endblock %}

templates/home.html
{%extends "base.html"%} {%block content%}
<h1>Hello, world! my name is {{name}}</h1>
<ul class="list-group list-group-horizontal">
  {% for element in my_list %}
  <li class="list-group-item">List element: {{ element }}</li>
</ul>
{% endfor %} {%endblock%}

templates/order.html
{%extends "base.html"%} {%block content%}

<h1>Order Info</h1>
<p>Order ID: {{order.id}}</p>
<p>Customer ID: {{order.customer_id}}</p>
<p>Total: {{order.total()}}</p>
<p>Items:</p>
<ul>
  {% for item in order.items %}
  <li>
    {{item.product.name}} - {{item.quantity}} - {{item.product.price}} -
    {{item.product.available}}
  </li>
  {% endfor %}
</ul>
<form
  method="POST"
  action="{{url_for('api_orders.process_order', id=order.id)}}"
>
  <button type="submit" class="btn btn-primary" name="strategy" value="adjust">
    Process with adjust
  </button>
</form>
<form
  method="POST"
  action="{{url_for('api_orders.process_order', id=order.id)}}"
>
  <button type="submit" class="btn btn-primary" value="reject" name="strategy">
    Process with reject
  </button>
</form>
<form
  method="POST"
  action="{{url_for('api_orders.process_order', id=order.id)}}"
>
  <button type="submit" class="btn btn-primary" name="strategy" value="ignore">
    Process with ignore
  </button>
</form>
{%endblock%}

templates/orders.html
{% extends "base.html" %}
{% block content %}
<h1>Orders</h1>
<table class="table table-borderless">
    <thead>
        <tr>
          <th scope="col">Order ID</th>
          <th scope="col">Customer Name</th>
          <th scope="col">Total</th>
          <th scope="col">Created at</th>
          <th scope="col">Processed</th>
        </tr>
      </thead>
      <tbody>
{% for order in orders %}
        <tr>
        <th scope="row">{{order.id}}</th>
        <td>{{order.customer.name}}</td>
        <td>${{order.total()}}</td>
        <td>{{order.created_at}}</td>
        <td>{% if order.processed %}
                <p style="color: green;">Processed</p>
            {% else %}
                <p style="color: red;">Not processed</p>
            {% endif %}
        </td>
        <td><a href="{{url_for('html.orders_info', id=order.id)}}">Details</a></td>
        <td>
            <form method="POST" action="{{ url_for('api_orders.delete_order', id=order.id) }}"> 
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
          </td>  
        </tr>
{% endfor %}
        </tbody>
</table>
{% endblock %}

templates/products.html
{% extends "base.html" %} {% block content %}
<h1>Products</h1>
{% for product in products %}
<p>
  <span>{{ product.name }}</span>
  <span>{{ product.price }}</span>
  <span>{{ product.available }}</span>
</p>
{% endfor %} {% endblock %}